name: Generate Release Notes

on:
  workflow_call:
    inputs:
      repository:
        description: Name of application repository
        required: true
        type: string
      head-sha:
        description: Head commit sha
        required: true
        type: string
      base-sha:
        description: Base commit sha
        required: true
        type: string

jobs:
  get-commits-diff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: bestrand/shared-workflows
    - name: Create Release Notes
      id: release-notes
      uses: actions/github-script@v6
      env:
        REPO: ${{ inputs.repository }}
        BASE: ${{ inputs.base-sha }}
        HEAD: ${{ inputs.head-sha }}
      with:
        github-token: ${{ secrets.COMMIT_READ }}
        script: |
          const releaseNotes = require('./.github/js/releaseNotes.js');
          return await releaseNotes("${{ env.BASE }}", "${{ env.HEAD }}", "${{ env.REPO }}", github)
    - name: Get result
      run: echo ${{ toJSON(steps.release-notes.outputs.result) }}
